# Understanding Data

Data Understanding in Pandas is the first and most important step in Exploratory Data Analysis (EDA).
It helps you quickly inspect, summarize, and get insights about your dataset 
before applying any transformations or models.

### Load data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('India_Ecommerce_Unclean_Dataset.csv')
df

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
0,ORD00000001,28/09/2023,07/10/2023,Rohan Agarwal,rohan.agarwal769@yahoo.co.in,9.186701e+11,Chenai,KA,684090.0,NaN,...,119742.81,26.31,5.0,119742.81,92650.40,cash,NaN,Next Day,4.4,N
1,ORD00000002,2023-12-11,2023-12-12,suresh Kumar,suresh.kumar998yahoo.co.in,9.193598e+11,PUNE,Maharashtra,186238.0,East India,...,140712.99,4.39,12.0,984990.93,1054759.81,NaN,Pending,Next Day,4.5,1
2,ORD00000003,2021-10-24,2021-11-04,Sunita Nair,sunita.nair877@yahoo.co.in,9.173318e+11,Indore,Bihar,3803.0,north,...,15846.47,9.26,12.0,63385.88,64418.31,Debit Card,pending,Standard,1.2,NaN
3,ORD00000004,2024-03-31,2024-04-06,Pooja Das,pooja.das184gmail.com,9.171830e+11,Kolkata,Andhra Pradesh,739883.0,SOUTH,...,132045.51,17.80,0.0,1591319.56,1308064.68,Debit Card,Paid,Same Day,4.0,Yes
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,9.189122e+11,Ahemadabad,NaN,5454.0,NaN,...,66250.95,45.25,28.0,287771.80,201670.48,upi,NaN,Economy,2.2,No Return
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD00099996,NaN,NaN,Pooja Chopra,pooja.chopra868@gmail.com,9.180279e+11,Mumbai,TN,792197.0,SOUTH,...,32914.31,56.74,18.0,65828.62,33603.40,DEBIT CARD,Paid,standard,1.0,No Return
99996,ORD00036659,2022-05-21,2022-05-27,meena Rao,meena.rao409@hotmail.com,9.168083e+11,PUNE,NaN,614404.0,North,...,57356.55,31.30,5.0,401495.85,289619.03,Cash on Delivery,PAID,Standard,1.4,Yes
99997,ORD00099998,03-Oct-2023,14-Oct-2023,Rahul Patel,rahul.patel827@rediffmail.com,9.195276e+11,NaN,Bihar,250996.0,SOUTH,...,119512.97,22.06,12.0,1075616.73,938935.96,Credit Card,PAID,NaN,1.9,No Return
99998,ORD00099999,2023-10-25,2023-11-05,POOJA Gupta,pooja.gupta101@hotmail.com,9.171351e+11,DELHI,Kerala,990079.0,north,...,34764.23,21.12,18.0,34764.23,32357.99,NaN,Failed,Next Day,4.9,No Return
99999,ORD00100000,01-25-2024,02-06-2024,Kavya Reddy,kavya.reddy225@outlook.com,9.190548e+11,PUNE,Maharashtra,343131.0,Northeast,...,119670.92,57.04,0.0,718025.52,308463.76,DEBIT CARD,PAID,Express,4.2,1

### view the data

##### first and last rows

In [3]:
df.head()

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
0,ORD00000001,28/09/2023,07/10/2023,Rohan Agarwal,rohan.agarwal769@yahoo.co.in,9.186701e+11,Chenai,KA,684090.0,NaN,...,119742.81,26.31,5.0,119742.81,92650.40,cash,NaN,Next Day,4.4,N
1,ORD00000002,2023-12-11,2023-12-12,suresh Kumar,suresh.kumar998yahoo.co.in,9.193598e+11,PUNE,Maharashtra,186238.0,East India,...,140712.99,4.39,12.0,984990.93,1054759.81,NaN,Pending,Next Day,4.5,1
2,ORD00000003,2021-10-24,2021-11-04,Sunita Nair,sunita.nair877@yahoo.co.in,9.173318e+11,Indore,Bihar,3803.0,north,...,15846.47,9.26,12.0,63385.88,64418.31,Debit Card,pending,Standard,1.2,NaN
3,ORD00000004,2024-03-31,2024-04-06,Pooja Das,pooja.das184gmail.com,9.171830e+11,Kolkata,Andhra Pradesh,739883.0,SOUTH,...,132045.51,17.80,0.0,1591319.56,1308064.68,Debit Card,Paid,Same Day,4.0,Yes
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,9.189122e+11,Ahemadabad,NaN,5454.0,NaN,...,66250.95,45.25,28.0,287771.80,201670.48,upi,NaN,Economy,2.2,No Return

In [4]:
df.tail()

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
99995,ORD00099996,NaN,NaN,Pooja Chopra,pooja.chopra868@gmail.com,9.180279e+11,Mumbai,TN,792197.0,SOUTH,...,32914.31,56.74,18.0,65828.62,33603.40,DEBIT CARD,Paid,standard,1.0,No Return
99996,ORD00036659,2022-05-21,2022-05-27,meena Rao,meena.rao409@hotmail.com,9.168083e+11,PUNE,NaN,614404.0,North,...,57356.55,31.30,5.0,401495.85,289619.03,Cash on Delivery,PAID,Standard,1.4,Yes
99997,ORD00099998,03-Oct-2023,14-Oct-2023,Rahul Patel,rahul.patel827@rediffmail.com,9.195276e+11,NaN,Bihar,250996.0,SOUTH,...,119512.97,22.06,12.0,1075616.73,938935.96,Credit Card,PAID,NaN,1.9,No Return
99998,ORD00099999,2023-10-25,2023-11-05,POOJA Gupta,pooja.gupta101@hotmail.com,9.171351e+11,DELHI,Kerala,990079.0,north,...,34764.23,21.12,18.0,34764.23,32357.99,NaN,Failed,Next Day,4.9,No Return
99999,ORD00100000,01-25-2024,02-06-2024,Kavya Reddy,kavya.reddy225@outlook.com,9.190548e+11,PUNE,Maharashtra,343131.0,Northeast,...,119670.92,57.04,0.0,718025.52,308463.76,DEBIT CARD,PAID,Express,4.2,1

##### random sample

In [37]:
df.sample(8)

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
24748,ORD00024749,2022-11-29,2022-12-13,Deepa Gupta,deepa.gupta176@hotmail.com,9.185904e+11,Lucknow,NaN,595594.0,Central,...,37490.11,45.74,0.0,74980.22,40684.27,EMI,NaN,NaN,4.3,N
39531,ORD00039532,2023-09-21,2023-09-23,Meena Verma,meena.verma547@rediffmail.com,9.189685e+11,Bangalore,Tamil Nadu,870513.0,South,...,INR 48370.33,10.50,12.0,241851.65,242432.09,Debit Card,paid,NaN,1.8,NaN
30129,ORD00030130,2020-09-12,2020-09-19,Arun Kumar,arun.kumar679@outlook.com,9.167317e+11,Bhopal,West Bengal,954169.0,SOUTH,...,19738.63,0.71,28.0,138170.41,175602.43,COD,PAID,Express,4.4,Yes
49297,ORD00049298,2023-02-15,2023-02-22,Rohan Agarwal,rohan.agarwal904@outlook.com,9.165184e+11,Ahemadabad,Kerala,460945.0,East India,...,27511.05,22.35,0.0,27511.05,21362.33,Cash on Delivery,pending,Standard,2.0,1
29264,ORD00029265,2020-01-13,2020-01-23,Sunita Rao,sunita.rao686@outlook.com,9.197306e+11,Delhi,MH,121773.0,SOUTH,...,42312.46,26.23,12.0,126937.38,NaN,Net Banking,pending,standard,3.7,N
40989,ORD00040990,21-Sep-2022,26-Sep-2022,Deepa Pillai,deepa.pillai174@hotmail.com,9.171648e+11,NaN,DL,526573.0,Northeast,...,18520.26,24.88,18.0,74081.04,65666.62,Debit Card,Complete,NaN,1.2,Y
58731,ORD00058732,2021-12-12,2021-12-13,Divya Mehta,divya.mehta563@gmail.com,9.182304e+11,NaN,WB,117818.0,West,...,37081.38,1.18,18.0,259569.66,302677.95,COD,Pending,Economy,1.4,No
311,ORD00000312,2023/10/28,2023/11/05,Kavya Kumar,kavya.kumar674@outlook.com,9.177428e+11,Vadodara,Gujarat,747598.0,West,...,73895.18,52.70,5.0,73895.18,36700.04,credit card,Complete,Express,6.1,Returned

### Check shape & structure

##### shape (rows, columns)

In [7]:
df.shape

(100000, 25)

##### columns name

In [8]:
df.columns

Index(['Order_ID', 'Order_Date', 'Delivery_Date', 'Customer_Name',
       'Customer_Email', 'Customer_Phone', 'Customer_City', 'Customer_State',
       'Customer_Pincode', 'Region', 'Category', 'Sub_Category',
       'Product_Name', 'Product_SKU', 'Quantity', 'Unit_Price_INR',
       'Discount_Percent', 'Tax_Percent', 'Gross_Amount_INR', 'Net_Amount_INR',
       'Payment_Method', 'Payment_Status', 'Shipping_Method',
       'Customer_Rating', 'Return_Status'],
      dtype='object')

##### data types

In [9]:
df.dtypes

Order_ID             object
Order_Date           object
Delivery_Date        object
Customer_Name        object
Customer_Email       object
Customer_Phone      float64
Customer_City        object
Customer_State       object
Customer_Pincode    float64
Region               object
Category             object
Sub_Category         object
Product_Name         object
Product_SKU          object
Quantity              int64
Unit_Price_INR       object
Discount_Percent    float64
Tax_Percent         float64
Gross_Amount_INR    float64
Net_Amount_INR      float64
Payment_Method       object
Payment_Status       object
Shipping_Method      object
Customer_Rating     float64
Return_Status        object
dtype: object

### Dataset Summary Info

**Gives:**

Total rows

Column names

Data types

Non-null values

**Help identify:**

Missing values count

wrong data types

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order_ID          99500 non-null   object
 1   Order_Date        98990 non-null   object
 2   Delivery_Date     97031 non-null   object
 3   Customer_Name     99014 non-null   object
 4   Customer_Email    99018 non-null   object
 5   Customer_Phone    98996 non-null   float64
 6   Customer_City     93215 non-null   object
 7   Customer_State    88108 non-null   object
 8   Customer_Pincode  99035 non-null   float64
 9   Region            81744 non-null   object
 10  Category          93659 non-null   object
 11  Sub_Category      98995 non-null   object
 12  Product_Name      97992 non-null   object
 13  Product_SKU       100000 non-null  object
 14  Quantity          100000 non-null  int64
 15  Unit_Price_INR    99500 non-null   object
 16  Discount_Percent  98926 non-null   float64
 17  Tax_Percent       98027 non-null   float64
 18  Gross_Amount_INR  100000 non-null  float64
 19  Net_Amount_INR    97045 non-null   float64
 20  Payment_Method    86780 non-null   object
 21  Payment_Status    82047 non-null   object
 22  Shipping_Method   77579 non-null   object
 23  Customer_Rating   98006 non-null   float64
 24  Return_Status     90628 non-null   object
dtypes: float64(7), int64(1), object(17)
memory usage: 19.1+ MB

### Statistical summary

##### numerical columns

In [11]:
df.describe()

,Customer_Phone,Customer_Pincode,Quantity,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Customer_Rating
count,9.899600e+04,99035.000000,100000.000000,98926.000000,98027.000000,1.000000e+05,9.704500e+04,98006.000000
mean,8.993317e+11,527900.944262,6.189760,31.663346,12.631714,4.794456e+05,3.718308e+05,3.035506
std,1.295726e+11,277762.101224,22.116066,25.363916,9.839965,1.941093e+06,1.608757e+06,1.488470
min,1.030000e+02,103.000000,-9.000000,-196.870000,0.000000,0.000000e+00,-1.824893e+07,-10.000000
25%,9.169359e+11,297091.500000,3.000000,14.720000,5.000000,1.182421e+05,8.275352e+04,2.000000
50%,9.179565e+11,532496.000000,5.000000,30.250000,12.000000,2.863406e+05,2.113656e+05,3.000000
75%,9.189785e+11,766195.000000,7.000000,45.790000,18.000000,5.661988e+05,4.317752e+05,4.000000
max,9.200000e+11,999993.000000,499.000000,199.850000,28.000000,7.307701e+07,9.353857e+07,10.000000

##### categorical columns

In [12]:
df.describe(include = 'O')

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_City,Customer_State,Region,Category,Sub_Category,Product_Name,Product_SKU,Unit_Price_INR,Payment_Method,Payment_Status,Shipping_Method,Return_Status
count,99500,98990,97031,99014,99018,93215,88108,81744,93659,98995,97992,100000,99500,86780,82047,77579,90628
unique,96590,7819,7901,1200,96745,28,22,9,15,50,39860,60513,99205,13,9,7,10
top,ORD00058265,2021-12-23,2022-09-09,Priya Joshi,rahul.sharma216@hotmail.com,Kanpur,WB,South,Electronics,Action Figures,Beauty - Makeup Model 378,SKU39569,121788.45,cash,Pending,Express,FALSE
freq,4,70,69,271,3,3432,4071,9236,6432,2064,10,9,2,6781,9284,11171,9207

##### all columns

In [13]:
df.describe(include = 'all')

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
count,99500,98990,97031,99014,99018,9.899600e+04,93215,88108,99035.000000,81744,...,99500,98926.000000,98027.000000,1.000000e+05,9.704500e+04,86780,82047,77579,98006.000000,90628
unique,96590,7819,7901,1200,96745,NaN,28,22,NaN,9,...,99205,NaN,NaN,NaN,NaN,13,9,7,NaN,10
top,ORD00058265,2021-12-23,2022-09-09,Priya Joshi,rahul.sharma216@hotmail.com,NaN,Kanpur,WB,NaN,South,...,121788.45,NaN,NaN,NaN,NaN,cash,Pending,Express,NaN,FALSE
freq,4,70,69,271,3,NaN,3432,4071,NaN,9236,...,2,NaN,NaN,NaN,NaN,6781,9284,11171,NaN,9207
mean,NaN,NaN,NaN,NaN,NaN,8.993317e+11,NaN,NaN,527900.944262,NaN,...,NaN,31.663346,12.631714,4.794456e+05,3.718308e+05,NaN,NaN,NaN,3.035506,NaN
std,NaN,NaN,NaN,NaN,NaN,1.295726e+11,NaN,NaN,277762.101224,NaN,...,NaN,25.363916,9.839965,1.941093e+06,1.608757e+06,NaN,NaN,NaN,1.488470,NaN
min,NaN,NaN,NaN,NaN,NaN,1.030000e+02,NaN,NaN,103.000000,NaN,...,NaN,-196.870000,0.000000,0.000000e+00,-1.824893e+07,NaN,NaN,NaN,-10.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,9.169359e+11,NaN,NaN,297091.500000,NaN,...,NaN,14.720000,5.000000,1.182421e+05,8.275352e+04,NaN,NaN,NaN,2.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,9.179565e+11,NaN,NaN,532496.000000,NaN,...,NaN,30.250000,12.000000,2.863406e+05,2.113656e+05,NaN,NaN,NaN,3.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,9.189785e+11,NaN,NaN,766195.000000,NaN,...,NaN,45.790000,18.000000,5.661988e+05,4.317752e+05,NaN,NaN,NaN,4.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,9.200000e+11,NaN,NaN,999993.000000,NaN,...,NaN,199.850000,28.000000,7.307701e+07,9.353857e+07,NaN,NaN,NaN,10.000000,NaN

### Row Index

In [14]:
df.index

RangeIndex(start=0, stop=100000, step=1)

### Missing Values Analysis

In [15]:
df.isnull()

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_Phone,Customer_City,Customer_State,Customer_Pincode,Region,...,Unit_Price_INR,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Payment_Method,Payment_Status,Shipping_Method,Customer_Rating,Return_Status
0,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,False,True,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
99996,False,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
99997,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,True,False,False
99998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
99999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [16]:
df.isnull().sum()

Order_ID              500
Order_Date           1010
Delivery_Date        2969
Customer_Name         986
Customer_Email        982
Customer_Phone       1004
Customer_City        6785
Customer_State      11892
Customer_Pincode      965
Region              18256
Category             6341
Sub_Category         1005
Product_Name         2008
Product_SKU             0
Quantity                0
Unit_Price_INR        500
Discount_Percent     1074
Tax_Percent          1973
Gross_Amount_INR        0
Net_Amount_INR       2955
Payment_Method      13220
Payment_Status      17953
Shipping_Method     22421
Customer_Rating      1994
Return_Status        9372
dtype: int64

##### percentage of missing values

In [19]:
(df.isnull().sum() / len(df)) * 100

Order_ID             0.500
Order_Date           1.010
Delivery_Date        2.969
Customer_Name        0.986
Customer_Email       0.982
Customer_Phone       1.004
Customer_City        6.785
Customer_State      11.892
Customer_Pincode     0.965
Region              18.256
Category             6.341
Sub_Category         1.005
Product_Name         2.008
Product_SKU          0.000
Quantity             0.000
Unit_Price_INR       0.500
Discount_Percent     1.074
Tax_Percent          1.973
Gross_Amount_INR     0.000
Net_Amount_INR       2.955
Payment_Method      13.220
Payment_Status      17.953
Shipping_Method     22.421
Customer_Rating      1.994
Return_Status        9.372
dtype: float64

### Duplication Data

In [20]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [22]:
df.duplicated().sum()

0

### Unique Values

In [24]:
df.nunique()

Order_ID            96590
Order_Date           7819
Delivery_Date        7901
Customer_Name        1200
Customer_Email      96745
Customer_Phone      98806
Customer_City          28
Customer_State         22
Customer_Pincode    93173
Region                  9
Category               15
Sub_Category           50
Product_Name        39860
Product_SKU         60513
Quantity              298
Unit_Price_INR      99205
Discount_Percent     8745
Tax_Percent             5
Gross_Amount_INR    99373
Net_Amount_INR      96472
Payment_Method         13
Payment_Status          9
Shipping_Method         7
Customer_Rating       139
Return_Status          10
dtype: int64

##### unique values in a specific column

In [25]:
df['Region'].unique()

array([nan, 'East India', 'north', 'SOUTH', 'East', 'Central',
       'Northeast', 'North', 'West', 'South'], dtype=object)

In [26]:
df['Tax_Percent'].unique()

array([ 5., 12.,  0., 28., 18., nan])

### Value Counts (Categorical Understanding)

In [39]:
df['Shipping_Method'].value_counts()

Shipping_Method
Express     11171
Same Day    11128
Next Day    11122
Economy     11106
standard    11060
EXPRESS     11026
Standard    10966
Name: count, dtype: int64

In [27]:
df['Customer_City'].value_counts()

Customer_City
Kanpur           3432
Ahemadabad       3390
Nagpur           3386
kolkata          3380
Vadodara         3374
Visakhapatnam    3370
Lucknow          3369
Ghaziabad        3366
Thane            3364
Chenai           3360
PUNE             3357
Mumbai           3340
Hyderabad        3338
Indore           3332
Kolkata          3330
Jaipur           3329
Patna            3326
Bangalore        3321
Bangalroe        3309
Delhi            3299
Chennai          3296
Hydrabad         3296
Bhopal           3294
Ahmedabad        3280
mumbai           3276
Surat            3250
DELHI            3240
Pune             3211
Name: count, dtype: int64

In [31]:
df['Category'].value_counts()

Category
Electronics               6432
BOOKS                     6372
Home&Kitchen              6362
Sports                    6347
Home & Kitchen            6319
Beauty                    6281
Health                    6259
Automotive                6216
FASHION                   6212
Grocery                   6181
Books                     6179
beauty & personal care    6153
Toys                      6131
Fashion                   6108
electronics               6107
Name: count, dtype: int64

## Check Column Types for Analysis

##### Separate numerical & categorical

In [34]:
num_cols = df.select_dtypes(include=['int64','float64'])
cat_cols = df.select_dtypes(include=['object'])

In [35]:
num_cols

,Customer_Phone,Customer_Pincode,Quantity,Discount_Percent,Tax_Percent,Gross_Amount_INR,Net_Amount_INR,Customer_Rating
0,9.186701e+11,684090.0,1,26.31,5.0,119742.81,92650.40,4.4
1,9.193598e+11,186238.0,7,4.39,12.0,984990.93,1054759.81,4.5
2,9.173318e+11,3803.0,4,9.26,12.0,63385.88,64418.31,1.2
3,9.171830e+11,739883.0,9,17.80,0.0,1591319.56,1308064.68,4.0
4,9.189122e+11,5454.0,4,45.25,28.0,287771.80,201670.48,2.2
...,...,...,...,...,...,...,...,...
99995,9.180279e+11,792197.0,2,56.74,18.0,65828.62,33603.40,1.0
99996,9.168083e+11,614404.0,7,31.30,5.0,401495.85,289619.03,1.4
99997,9.195276e+11,250996.0,9,22.06,12.0,1075616.73,938935.96,1.9
99998,9.171351e+11,990079.0,-1,21.12,18.0,34764.23,32357.99,4.9
99999,9.190548e+11,343131.0,6,57.04,0.0,718025.52,308463.76,4.2

In [36]:
cat_cols

,Order_ID,Order_Date,Delivery_Date,Customer_Name,Customer_Email,Customer_City,Customer_State,Region,Category,Sub_Category,Product_Name,Product_SKU,Unit_Price_INR,Payment_Method,Payment_Status,Shipping_Method,Return_Status
0,ORD00000001,28/09/2023,07/10/2023,Rohan Agarwal,rohan.agarwal769@yahoo.co.in,Chenai,KA,NaN,Beauty,Makeup,Beauty - Makeup Model 917,SKU49209,119742.81,cash,NaN,Next Day,N
1,ORD00000002,2023-12-11,2023-12-12,suresh Kumar,suresh.kumar998yahoo.co.in,PUNE,Maharashtra,East India,Health,Ayurveda,Health - Ayurveda Model 993,SKU14872,140712.99,NaN,Pending,Next Day,1
2,ORD00000003,2021-10-24,2021-11-04,Sunita Nair,sunita.nair877@yahoo.co.in,Indore,Bihar,north,Electronics,Mobiles,Electronics - Mobiles Model 422,SKU83420,15846.47,Debit Card,pending,Standard,NaN
3,ORD00000004,2024-03-31,2024-04-06,Pooja Das,pooja.das184gmail.com,Kolkata,Andhra Pradesh,SOUTH,Toys,RC Toys,Toys - RC Toys Model 453,SKU54566,132045.51,Debit Card,Paid,Same Day,Yes
4,ORD00000005,07-01-2022,07-11-2022,Kavya Sen,kavya.sen379@hotmail.com,Ahemadabad,NaN,NaN,Sports,Cricket,Sports - Cricket Model 962,SKU63091,66250.95,upi,NaN,Economy,No Return
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,ORD00099996,NaN,NaN,Pooja Chopra,pooja.chopra868@gmail.com,Mumbai,TN,SOUTH,Toys,Action Figures,Toys - Action Figures Model 991,SKU24431,32914.31,DEBIT CARD,Paid,standard,No Return
99996,ORD00036659,2022-05-21,2022-05-27,meena Rao,meena.rao409@hotmail.com,PUNE,NaN,North,beauty & personal care,Outdoor,Sports - Outdoor Model 897,SKU69473,57356.55,Cash on Delivery,PAID,Standard,Yes
99997,ORD00099998,03-Oct-2023,14-Oct-2023,Rahul Patel,rahul.patel827@rediffmail.com,NaN,Bihar,SOUTH,BOOKS,Children,Books - Children Model 604,SKU37590,119512.97,Credit Card,PAID,NaN,No Return
99998,ORD00099999,2023-10-25,2023-11-05,POOJA Gupta,pooja.gupta101@hotmail.com,DELHI,Kerala,north,Sports,Yoga,Sports - Yoga Model 312,SKU13983,34764.23,NaN,Failed,Next Day,No Return
99999,ORD00100000,01-25-2024,02-06-2024,Kavya Reddy,kavya.reddy225@outlook.com,PUNE,Maharashtra,Northeast,Fashion,Watches,NaN,SKU42487,119670.92,DEBIT CARD,PAID,Express,1